### ISSUE TITLE
Add user help documentation

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#139]
Add user help docs to allow CMS editors to understand how to add and manage blocks in a website using elemental and this module.

## Tasks

- [ ] Create documentation
- [ ] Add screenshots
- [ ] Add to SS4 version of userhelp.silverstripe.org (github.com/silverstripe/silverstripe-userhelp-content)

## Acceptance criteria

- [ ] Docs exist in `docs/en/` 
- [ ] Docs are written in markdown
- [ ] Screenshots represent the latest state of the blocks
- [ ] Documentation is added to userhelp
