### ISSUE TITLE
Convert ElementalEditor GridField to a React based equivalent

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#272]
Prior to beginning work on inline editing of content blocks, we'll need to:

Create a new react app - e.g. ElementalEditor and power as much of this with React, GraphQL and form factory/schema as possible now to pave the way for the react driven CMS in future.

We don't need to continue using gridfield for elemental, particularly because the editor only really has one column.

## Acceptance criteria

- [x] Keep current styling, but update where it makes sense
- [x] Re-build current functionality to be utilising React
- [x] Page will have one elemental area
- [x] Behat tests
- [x] Extensible
- drag and drop isn't expected to work on completion of this issue (see #285)

## Subtasks

- [x] Branch master -> 3 for 3.x support and make master 4.x @robbieaverill
- [x] Add necessary GraphQL query configuration and query HOC #274 @robbieaverill #274
- [x] Bind GraphQL query to ElementList container @robbieaverill #277
- [x] Create all empty React components and containers #275 @ScopeyNZ
- [x] Create skeleton ElementEditor container #275 @ScopeyNZ
- [x] Create skeleton ElementList container #275 @ScopeyNZ
- [x] Create skeleton Element container #275 @ScopeyNZ
- [x] Create skeleton Toolbar container #275 @ScopeyNZ
- [x] Create skeleton Header component #275 @ScopeyNZ @raissanorth
- [x] Create skeleton Content component #275 @ScopeyNZ
- [x] Create skeleton AddNew component #275 @ScopeyNZ
- [x] Implement current markup and CSS for ElementEditor @ScopeyNZ
- [x] Implement current markup and CSS for ElementList #284
- [x] Implement current markup and CSS for Element #284 @raissanorth
- [x] Implement current markup and CSS for Toolbar #281 @ScopeyNZ
- [x] Implement current markup and CSS for Header #278 @raissanorth
- [x] Implement current markup and CSS for Content #284 @raissanorth
- [x] Implement current markup and CSS for AddNew #281 @ScopeyNZ
- [x] Add start of upgrade guide (contribute to it ongoing) #283 
- [x] Enable delete action from block level
- [x] Edit ability (via GridFieldDetailForm) still works

**Comment by robbieaverill** [comment]
Clarification on an acceptance criteria point:

>(A/C) Page will have one elemental area

Elemental currently supports multiple elemental areas per page, but only provides one out of the box.

We'll implement this in a way that works for the default ElementalArea relationship, but attempt to document how devs can add more elemental editors for extra relationships they want to add.

It's unlikely to be as easy as it was with PHP GridFields.

**Comment by robbieaverill** [comment]
>Edit ability (via GridFieldDetailForm) still works

We looked at removing GridField as a backend as part of this work, but until we have a React replacement for an edit form we'll need to keep it there to support blocks that won't be able to be edited inline (such as userform blocks).

For more info, see https://github.com/silverstripe/silverstripe-admin/issues/590
