### ISSUE TITLE
Save or publish blocks individually

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#290]
## User Story
As a CMS user, I want to be able to save or publish blocks individually at a page level, so that I can update content on a page independently of other blocks being edited. 

Part of #295

## Acceptance Criteria
- [ ] The (...) icon includes the following functionality:
 - Save 
 - Publish
 - Unpublish
 - Archive
- [ ] Clicking ‘Save’ records the current state of the individual block content as a draft  #296 
- [x] Clicking ‘Publish’ records the current state of the individual block content on the site #297
- [x] Clicking ‘Unpublish’ removes the individual block content from the site #298
- [x] Clicking ‘Archive’ removes the individual block content from the site and removes the block from the CMS page, and archives it(?) #299
- [ ] Styling is as per wireframe: https://projects.invisionapp.com/share/ZRL4T2HQAGB#/screens/301923101
- [ ] Block contents can still be saved/published via the page buttons

**Comment by robbieaverill** [comment]
I've subtasked out each of the four actions into their own tickets

**Comment by robbieaverill** [comment]
I think we can close this now, the remaining task is "Save" which is being worked on at the moment with #296, so we can track it there
